SET SCHEMA FN71837@

--TRIGGER1--
CREATE TRIGGER UPD_MGR_SAL
AFTER DELETE ON FIGHTERS
REFERENCING OLD AS O
FOR EACH ROW
WHEN(O.WORKCOMP = 'UFC')
	UPDATE COMPANIES
	SET MGR_SALARY = MGR_SALARY - 20000
	WHERE COMPNAME = 'UFC'@

DELETE FROM FIGHTERS WHERE FNO = '016'@
	
SELECT * FROM FIGHTERS@
SELECT * FROM COMPANIES@

UPDATE COMPANIES
SET MGR_SALARY = MGR_SALARY - 20000
WHERE COMPNAME = 'UFC'@

DROP TRIGGER UPD_MGR_SAL@

--TRIGGER2--
CREATE PROCEDURE CHECK_BONUS (IN v_fno ANCHOR FIGHTERS.FNO)
BEGIN
 DECLARE F_RECORD INT;
 DECLARE MIN_FIGHTS INT DEFAULT 20;
 
 SELECT WINS + LOSES
 INTO F_RECORD
 FROM FIGHTERS
 WHERE FNO = v_fno;
 
 IF F_RECORD < MIN_FIGHTS THEN
  SIGNAL SQLSTATE '45000'
 SET MESSAGE_TEXT = 'Not enough fights for a bonus!';
 END IF;
 END@


CREATE TRIGGER ADD_BONUS
BEFORE UPDATE
ON FIGHTERS
FOR EACH ROW
BEGIN
    CALL FN71837.CHECK_BONUS ('001');
END@

DROP TRIGGER ADD_BONUS@
DROP PROCEDURE CHECK_BONUS@


UPDATE FIGHTERS
SET SALARY = SALARY + 10000
WHERE FNO = '001'@

SELECT * FROM FIGHTERS@
 
