SET SCHEMA FN71837@

--FUNCTION1--
CREATE FUNCTION FIGHTER_INFO (v_workcomp VARCHAR(10))
RETURNS TABLE(LASTNAME VARCHAR(15), SALARY DECIMAL(9,2))
RETURN
SELECT LASTNAME, SALARY
FROM FIGHTERS
WHERE WORKCOMP = v_workcomp AND SEX = 'M'@  

SELECT * FROM TABLE (FN71837.FIGHTER_INFO(VARCHAR('ACA')))@

SELECT * FROM FIGHTERS@
DROP FUNCTION FIGHTER_INFO@

--FUNCTION2--
CREATE FUNCTION FIGHTER_AGE(v_fno CHAR(3))
RETURNS INT
RETURN
SELECT YEAR(CURRENT_DATE - BIRTHDATE) FROM FIGHTERS
WHERE FNO = v_fno@

SELECT LASTNAME,FN71837.FIGHTER_AGE(char('003')) AS AGE
FROM FIGHTERS
WHERE FNO = '003'@

DROP FUNCTION FIGHTER_AGE@
