SET SCHEMA FN71837@

CREATE TABLE FIGHTERS (
                 FNO  CHAR(3) NOT NULL, 
                 FIRSTNAME  VARCHAR(12) NOT NULL, 
                 LASTNAME  VARCHAR(15) NOT NULL, 
                 BIRTHDATE DATE,
                 SEX CHAR(1),
                 WORKCOMP VARCHAR(10),
                 WINS INT,
                 LOSES INT,
                 SALARY DECIMAL(9,2),
                 DIVISION VARCHAR(15) NOT NULL,
                 FSTATUS CHAR(2) NOT NULL,
                 COUNTRY VARCHAR(15),
                 CONSTRAINT  PK_FIGHTERS  PRIMARY KEY (FNO)
)@

DROP TABLE FIGHTERS@

CREATE TABLE COMPANIES (
				COMPNAME VARCHAR(20) NOT NULL,
				MANAGER VARCHAR(15) NOT NULL,
				MGR_SALARY DECIMAL(9,2),
				COMPLOC VARCHAR(25),
				STARNO CHAR(3) NOT NULL,
				CONSTRAINT PK_COMPANIES PRIMARY KEY(COMPNAME)
)@

DROP TABLE COMPANIES@

CREATE TABLE EVENTS (
				EVENTNO CHAR(5) NOT NULL,	
				COMPNAME VARCHAR(20) NOT NULL,
				EVENTLOC VARCHAR(10) NOT NULL,
				EVENTDATE DATE,
				TICKETPRICE DECIMAL(9,2),
				CONSTRAINT PK_EVENTS PRIMARY KEY(EVENTNO)		
)@

SELECT * FROM EVENTS@
DROP TABLE EVENTS@

CREATE TABLE FIGHTER_ACT (
				ACTNO SMALLINT NOT NULL,
				EVENTNO CHAR(5) NOT NULL,
				FFNO  CHAR(3) NOT NULL,
				SFNO CHAR(3) NOT NULL,
				WINNER VARCHAR(10)
)@

SELECT * FROM FIGHTER_ACT@

DROP TABLE FIGHTER_ACT@


ALTER TABLE  FIGHTERS  ADD CONSTRAINT  FK_FIGHTERS  
FOREIGN KEY (WORKCOMP) REFERENCES  COMPANIES (COMPNAME) ON DELETE SET NULL@

ALTER TABLE  COMPANIES  ADD CONSTRAINT  FK_COMPANIES  
FOREIGN KEY (STARNO) REFERENCES  FIGHTERS (FNO)@

ALTER TABLE  EVENTS  ADD CONSTRAINT  FK_EVENTS  
FOREIGN KEY (COMPNAME) REFERENCES  COMPANIES (COMPNAME)@

ALTER TABLE FIGHTER_ACT ADD CONSTRAINT FK_FIGHTER_ACT1
FOREIGN KEY (FFNO) REFERENCES FIGHTERS (FNO)@

ALTER TABLE FIGHTER_ACT ADD CONSTRAINT FK_FIGHTER_ACT2
FOREIGN KEY (SFNO) REFERENCES FIGHTERS (FNO)@

ALTER TABLE FIGHTER_ACT ADD CONSTRAINT FK_FIGHTER_ACT3
FOREIGN KEY (EVENTNO) REFERENCES EVENTS (EVENTNO)@

